CREATE TABLE sales (
    order_id INT,
    customer_id INT,
    amount DECIMAL
) PARTITION BY HASH (order_id);

CREATE TABLE sales_p1 PARTITION OF sales FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE sales_p2 PARTITION OF sales FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE sales_p3 PARTITION OF sales FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE sales_p4 PARTITION OF sales FOR VALUES WITH (MODULUS 4, REMAINDER 3);

INSERT INTO sales VALUES
    (1, 101, 100.50),
    (2, 102, 200.75),
    (3, 103, 150.25),
    (4, 104, 300.00),
    (5, 105, 250.50),
    (6, 106, 175.75),
    (7, 107, 400.25),
    (8, 108, 350.00);

    SELECT * FROM ONLY sales;
    SELECT * FROM sales;

SELECT * FROM sales_p1;
SELECT * FROM sales_p2;
SELECT * FROM sales_p3;

SELECT * FROM sales WHERE order_id = 3;


ALTER TABLE sales DETACH PARTITION sales_p3;

ALTER TABLE sales ATTACH PARTITION sales_p3 FOR VALUES WITH (MODULUS 4, REMAINDER 2);


